blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
   
    
    path("", views.ArticleListView.as_view(), name="members"),
    path("members/<slug:slug>/", views.ArticleDeatil.as_view(), name="detail"),
    path("preview/<int:pk>/", views.ArticlePreview.as_view(), name="preview"),
    path("category/<slug:slug>/", views.CategoryView.as_view(), name="category"),
    path("author/<slug:author>/", views.AuthorView.as_view(), name="author"),#url gets author name
    path("search/", views.SearchView.as_view(), name="search"),#url gets author name
    # path("category/<slug:slug>/page/<int:page>/", views.category, name="category"),
    
    
] 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  #  local
from django.conf import settings  # local
from accounts.views import Login, Register



urlpatterns = [
    path('admin/', admin.site.urls), #comment this in case Error for first Creating superuser
    path("", include("blog.urls")),
    path("login/", Login.as_view(redirect_authenticated_user=True), name="login"),#this must be upper than the line below
    path("", include("django.contrib.auth.urls")),#Login, Logout,...
    path("accounts/", include("accounts.urls")),
    # path('activate/<uidb64>/<token>/',  activate, name='activate'),     #Email comfirm
    path('register/',Register.as_view(redirect_authenticated_user=True), name="register" ),#SignUP
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # local

blog/models.py
from django.db import models
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django_jalali.db import models as jmodels
from extensions.utils import jalali_convertor
# from django.contrib.auth.models import User
from accounts.models import User
from django.urls import reverse 


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='P')
    def active(self):
        return self.filter(status=True)
    
class Category(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank = True, null=True, verbose_name=_(" زیردسته"), help_text="subcategory")
    title= models.CharField(max_length=255, verbose_name=_("عنوان"))
    slug = models.SlugField(max_length=255, unique=True, default='', help_text=("آدرس slug"),verbose_name=_("نامک")) 
    position = models.IntegerField(verbose_name=_("پوزیشن"), default=1) 
    status = models.BooleanField(default=True, verbose_name=_("نمایش داده شود"))
    class Meta:
        verbose_name = "دسته‌بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ["parent__id", "position"]
    def __str__(self):
        return self.title
    objects = ArticleManager()
    
class Member(models.Model):# Articles
    STATUS = [
        ("P", "انتشار"),         # publish
        ("D", "پیش نویس"),       # draft
        ("I", "درحال بررسی"),    # investigate
        ("B", "برگشت داده‌شده"),  # back
    ]
    title= models.CharField(max_length=255, verbose_name=_("عنوان"))
    description = models.TextField(blank=True, null=True, verbose_name=_("توضیحات"))
    slug = models.SlugField(max_length=255, unique=True, default='', help_text=("آدرس slug"),verbose_name=_("نامک")) 
    category = models.ManyToManyField(Category, verbose_name=_("دسته بندی ها"), related_name='articles', blank=True)
    author = models.ForeignKey(User,verbose_name=_("نویسنده"),on_delete=models.CASCADE,null=True,related_name='articles',)
    
    # created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("تاریخ انتشار"))
    # updated_at = models.DateTimeField(auto_now=True)
    created_at = jmodels.jDateTimeField(auto_now_add=True, verbose_name=_("تاریخ انتشار"))#False: showing the calender
    updated_at = jmodels.jDateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS, verbose_name=_("وضعیت"))
    photo = models.ImageField(upload_to="photo/", verbose_name=_("تصاویر"), blank=True, null=True)
    is_special = models.BooleanField(default=False, verbose_name= _("مقاله ویژه") )
    class Meta:
        verbose_name = _("مقاله")
        verbose_name_plural = _("مقاله ها ")
    def __str__(self):
        return self.title
    def get_categories(self):
        return  ",".join([i.title for i in self.category.filter(status=True)])

    get_categories.short_description = _("دسته بندی ها")
    objects = ArticleManager()
    def get_absolute_url(self): # new
        return reverse('accounts:home')

class Settings(models.Model):
    title= models.CharField(max_length=255, verbose_name=_("عنوان سایت "), help_text="عنوان سایت در قسمت navbar")
    class Meta:
        verbose_name = _("عنوان سایت")
        verbose_name_plural = _("عنوان سایت")
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Member, Category, User
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from accounts.mixins import AccessMixin
from django.db.models import  Q
from datetime import datetime , timedelta
from django.utils.translation import activate
def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")



class ArticleListView(ListView):
    queryset = Member.objects.published()
    paginate_by = 3 


class ArticleDeatil(DetailView):
    # template_name = "blog/post.html"
    # context_object_name = "object_list"
    def get_object(self):
        self.slug = self.kwargs["slug"]
        article = get_object_or_404(Member, slug=self.slug, status="P")
        return article

class ArticlePreview(AccessMixin, DetailView):
    def get_object(self):
        self.pk = self.kwargs["pk"]
        return Member.objects.get(pk= self.pk)


class CategoryView(ListView):
    paginate_by = 1
    template_name = "blog/category.html"
    def get_queryset(self):
        self.slug = self.kwargs["slug"]
        category = get_object_or_404(Category, status=True, slug = self.slug)#Category.objects.all() won't work we need only one object
        return category.articles.published()

class AuthorView(ListView):
    paginate_by = 3 
    template_name = "blog/author_list.html"
    def get_queryset(self):
        global author
        userename = self.kwargs["author"]
        author = get_object_or_404(User,  username = userename)
        return author.articles.published()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["author"] =  author
        return context

class SearchView(ListView):
    paginate_by = 1
    template_name = "blog/search_list.html"
    def get_queryset(self):
        global search
        search = self.request.GET.get('q', "")  #q is specified in the <input name='q'... and url: http://.../search/?q=< words > 
        return Member.objects.published().filter(Q(description__icontains=search) | Q(title__icontains=search))
    def get_context_data(self, **kwargs): #sending extra context
        context = super().get_context_data(**kwargs)
        context["search_title"] =  search
        return context
    
    
    

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/author_list.html
{% extends 'blog/list.html' %}

templates/blog/base.html
{% load static %}
{% load base_tags %}
{% comment %} {% load i18n %} {% endcomment %}
<!DOCTYPE html>

<html lang="en">
   
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>سلسیوم  {% block title %}{% endblock title %}</title>
        <link rel="icon" type="image/x-icon" href="{%  static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet"/>
         <!-- Star Rating (django-star-rating)-->
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>




    </head>
    
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:members' %}">{%title%}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                   
                    <ul class="navbar-nav ms-auto py-4 py-lg-0" id="nav">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:members' %}">Home</a></li>
{%navbar%}

<form class="form-inline mt-3" action="{% url 'blog:search' %}">
    <input type="text" name="q" class="form-control" palceholder="جستجو" value = {{search_title}}>
    <button class="btn btn-success" style="padding:8px; border-radius:5px;margin-right:5px">جستجو</button>
</form>



                    </ul>
                 
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% block header %}
        
        {% endblock header %}
        <!-- Main Content-->
        {% comment %} <div class="sidebar_parent">
            sidebar parent
            {#%popular_articles%#}
            {#%hot_articles%#}
            {#%stars_articles%#}
        </div> {% endcomment %}
        {% block main_content %}{% endblock main_content %}
       
        {% block post_content %}{% endblock post_content %}
 
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>

templates/blog/category.html
{% extends 'blog/list.html' %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load jformat %}
{% load static %}
{#% load ratings %#}
{% load base_tags %}
{% load humanize %}
{% load i18n %}

{% block header %}
<header class="masthead" style="background-image: url({% static 'blog/assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{% translate 'سایت جنگو' %}</h1>
                    
                    <span class="subheading">{% translate "یک سایت نوشته شده با جنگو" %}</span>
                    {% block search_title %}{% endblock search_title %}
                </div>
                
            </div>
        </div>
    </div>
    
</header>
{% endblock header %}

{% block main_content %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            
            
            <!-- Post preview-->
            
            {% comment %} {% for category in categories %} {% endcomment %}
            {% comment %} category.articles.all%  -> this will get unPublished(draft) post.{% endcomment %}
            {% comment %} {%for article in categories.articles.published%} {% endcomment %}
            {%for article in object_list%}
        
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title"> {{article.title}} 

                        {% if article.is_special %}
                        <span class="badge bg-danger" style="font-size:1.1rem">ویژه</span>
                        {% endif %}
                    </h2>
                    
                </a>
                {#% ratings article %#}
                <p class="post-subtitle">{{article.description|striptags|truncatewords:50}}</p>
                <p class="post-meta">
                    Posted by
                    {% comment %}  Author {% endcomment %}
                    <a href="{% url 'blog:author' article.author.username %}">{{article.author}}</a>
                    {% comment %} {{article.created_at|jformat:"%Y/%m/%d"}} {% endcomment %}
                    {{article.created_at|naturaltime}}

                    
                    
                    {% comment %} TODO: we can put condition if update_Time> Created time {% endcomment %}
                    
                
                </p>
                <p class="post-tags">
                    {% for cat in article.category.active %}
                    <a href="{% url 'blog:category' cat.slug %}"> {{cat}}#  </a>
                    {% endfor %}
                </p>
                
                    
                
                
                
            </div>
            {% empty %}
            هنور پستی منتشر نشده است
            {% endfor %}

            {% comment %} {% endfor %} {% endcomment %}
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            <div class="d-flex  justify-content-end mb-4">
                

                {%if page_obj.has_previous%}
                {% comment %} <a class="me-2" href="?page={{page_obj.previous_page_number}}">previous</a> {% endcomment %}
                <a class="me-2" href="?{% url_replace request 'page' page_obj.previous_page_number %}">قبلی</a>
                {% endif %}
                <p> صفحه {{page_obj.number}} از {{page_obj.paginator.num_pages }} </p>
                
                {%if page_obj.has_next%}
                {% comment %} <a class="me-2" href="?page={{page_obj.next_page_number}}">next  </a> {% endcomment %}
                <a class="me-2" href="?{% url_replace request 'page' page_obj.next_page_number %}">بعدی</a>
                {% comment %} <a class="me-2" href="?page={{page_obj.paginator.num_pages}}"> Last:{{page_obj.paginator.num_pages}}</a> {% endcomment %}
                <a class="me-2" href="?{% url_replace request 'page' page_obj.paginator.num_pages %}"> اخرین صفحه:{{page_obj.paginator.num_pages}}</a>
                
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock main_content %}

templates/blog/member_detail.html
{% extends 'blog/base.html' %}
{#% load comment_tags %#}  {# Loading the template tag #}
{#% load ratings %#}
{% block title %}
{{object.title}}
{% endblock title %}
{% block header %}

<header class="masthead" style="background-image: url('{% if object.photo  %}{{object.photo.url}}{% endif %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{object.title}}</h1>
                    <span class="meta">
                        نویسنده:
                        <a href="{% url 'blog:author' object.author %}">{% firstof  object.author.get_full_name object.author  %}</a>
                        {{object.created_at|date:'Y/m/d'}}
                        <br>
                        {#% ratings object %#}
                        <br>
‌
                        
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>


{% endblock header %}
        {% block post_content %}
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        
                        {% if object.is_special %}
                            {% if user.is_authenticated and user.is_special_user or user.is_superuser or user.pk == object.author.pk %}
                                {{object.description|safe}}
                            {% else %}
                            {{object.description|striptags|truncatewords:30}}
                                 <p class="badge bg-warning">  این پست مخصوص کاربران ویژه است  میتوانید از <a href="{% url "register" %}">اینجا ثبت نام</a> کنید</p>
                            {% endif %}
                        {% else %}
                        {{object.description|safe}}
                        {% endif %}
                    </div>
                    {#% render_comments object request %#} 
                </div>
            </div>
        </article>
        
        {% endblock post_content %}
        

templates/blog/member_list.html
{% extends 'blog/list.html' %}

templates/blog/search_list.html
{% extends 'blog/list.html' %}
{% block search_title %}
{% if  search_title not in "" %}
<span> جست جو برای : </span>{{ search_title }}
{% endif %}

{% endblock search_title %}